version: '3.3'

volumes:
  pg_data:

services:
  db:
    image: postgres:15.8
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_nw
  
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend_nw

networks:
  backend_nw:
    driver: bridge